### ISSUE TITLE
require('wastyle/dist/astyle.wasm') or .default ?

### ISSUE THREAD

**Issue by ThanrayTian** [Menci/wastyle#1]
在项目A中以webpack方式使用wastyle：
![image](https://user-images.githubusercontent.com/9781603/78329773-1d571c80-75b5-11ea-945f-84d2f5874360.png)

webpack打包项目A，在项目B中引用项目A：
![image](https://user-images.githubusercontent.com/9781603/78329752-13cdb480-75b5-11ea-87b5-1fb81731af94.png)
然后导致报错：
TypeError: WebAssembly.compile(): Argument 0 must be a buffer source

另外，readme中是第一种使用方式 require('wastyle/dist/astyle.wasm')，但在demo中是第二种使用方式 require('wastyle/dist/astyle.wasm').default 。
哪种是正确的呢？

**Comment by ThanrayTian** [comment]
TypeError: WebAssembly.compile(): Argument 0 must be a buffer source

**Comment by ThanrayTian** [comment]
另外问下，为什么不用wasm-loader呢

**Comment by Menci** [comment]
README 里没写 `require('wastyle/dist/astyle.wasm')` 啊

**Comment by Menci** [comment]
require 的话是需要 `.default` 的，见 https://github.com/NeekSandhu/onigasm/issues/2#issuecomment-594158655

**Comment by Menci** [comment]
不用 wasm-loader 的原因是，wasm-loader 不支持传入 imports，而 emscripten 编译出来的 WASM 程序是需要 WASI 接口的
